remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Hawaii Fanstand Support Page
description: This is the support page for The Fan Stand Kauai â€“ quick help with orders, refunds, and questions.
show_downloads: false
